// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VetCare.API.Data;

#nullable disable

namespace VetCare.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VetCare.API.Models.AlergiaCondicao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("PacienteId", "Ativa");

                    b.ToTable("AlergiasCondicoes");
                });

            modelBuilder.Entity("VetCare.API.Models.ApoioAdministrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("ApoiosAdministrativos");
                });

            modelBuilder.Entity("VetCare.API.Models.AtendimentoFisioterapeutico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaEdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalaDor")
                        .HasColumnType("integer");

                    b.Property<string>("EvolucaoClinica")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("integer");

                    b.Property<int?>("FrequenciaRespiratoria")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProximosPassos")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("SinaisVitais")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TecnicasAplicadas")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("TemperaturaCelsius")
                        .HasColumnType("numeric(8,2)");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId")
                        .IsUnique();

                    b.HasIndex("TratamentoId");

                    b.HasIndex("ProntuarioId", "DataRegistro");

                    b.HasIndex("VeterinarioId", "DataRegistro");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("VetCare.API.Models.AvaliacaoClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anamnese")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaEdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExameFisico")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("HipoteseDiagnostica")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PlanoTerapeutico")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueixaPrincipal")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId");

                    b.HasIndex("ProntuarioId", "DataRegistro");

                    b.HasIndex("VeterinarioId", "DataRegistro");

                    b.ToTable("AvaliacoesClinicas");
                });

            modelBuilder.Entity("VetCare.API.Models.BloqueioAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId", "Inicio", "Fim");

                    b.ToTable("BloqueiosAgenda");
                });

            modelBuilder.Entity("VetCare.API.Models.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoSessaoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<TimeSpan>("HorarioAbertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioFechamento")
                        .HasColumnType("interval");

                    b.Property<int>("HorasMinimasCancelamento")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("VetCare.API.Models.DocumentoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("DocumentosClinicos");
                });

            modelBuilder.Entity("VetCare.API.Models.ItemPrescricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PrescricaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("PrescricaoId");

                    b.ToTable("ItensPrescricao");
                });

            modelBuilder.Entity("VetCare.API.Models.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("DestinatarioId", "Lida");

                    b.HasIndex("RemetenteId", "DestinatarioId", "DataEnvio");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("VetCare.API.Models.MidiaSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("SessaoId");

                    b.ToTable("MidiasSessao");
                });

            modelBuilder.Entity("VetCare.API.Models.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkRelacionado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Visualizada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Visualizada", "DataCriacao");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("VetCare.API.Models.ObservacaoInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvaliacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("AutorId");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("ObservacoesInternas");
                });

            modelBuilder.Entity("VetCare.API.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Castrado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataObito")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Microchip")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Pelagem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal?>("PesoAtualKg")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("ClinicaId", "Ativo");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("VetCare.API.Models.Prescricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AtendimentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Orientacoes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ValidaAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("VeterinarioId");

                    b.HasIndex("ProntuarioId", "DataEmissao");

                    b.ToTable("Prescricoes");
                });

            modelBuilder.Entity("VetCare.API.Models.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("VetCare.API.Models.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId", "DataHora");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.HasIndex("UsuarioId", "DataHora");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("VetCare.API.Models.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LembreteEnviado")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId", "DataHora");

                    b.HasIndex("VeterinarioId", "DataHora");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("VetCare.API.Models.TokenRedefinicaoSenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UtilizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRedefinicaoSenha");
                });

            modelBuilder.Entity("VetCare.API.Models.Tratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjetivoTerapeutico")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ObservacoesGerais")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioId");

                    b.HasIndex("PacienteId", "Status");

                    b.ToTable("Tratamentos");
                });

            modelBuilder.Entity("VetCare.API.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("VetCare.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClinicaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ClinicaId", "Perfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VetCare.API.Models.Vacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("LembreteEnviado")
                        .HasColumnType("boolean");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProximaDose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("VeterinarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("VeterinarioId");

                    b.HasIndex("ProximaDose", "LembreteEnviado");

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("VetCare.API.Models.VersaoRegistroClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlteradoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConteudoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegistroId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("TipoRegistro", "RegistroId");

                    b.ToTable("VersoesRegistrosClinicos");
                });

            modelBuilder.Entity("VetCare.API.Models.Veterinario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Crmv")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("VetCare.API.Models.AlergiaCondicao", b =>
                {
                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany("AlergiasCondicoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("VetCare.API.Models.ApoioAdministrativo", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VetCare.API.Models.AtendimentoFisioterapeutico", b =>
                {
                    b.HasOne("VetCare.API.Models.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Tratamento", "Tratamento")
                        .WithMany()
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prontuario");

                    b.Navigation("Sessao");

                    b.Navigation("Tratamento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.AvaliacaoClinica", b =>
                {
                    b.HasOne("VetCare.API.Models.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Tratamento", "Tratamento")
                        .WithMany()
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prontuario");

                    b.Navigation("Tratamento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.BloqueioAgenda", b =>
                {
                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.DocumentoClinico", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnviadoPor");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("VetCare.API.Models.ItemPrescricao", b =>
                {
                    b.HasOne("VetCare.API.Models.Prescricao", "Prescricao")
                        .WithMany("Itens")
                        .HasForeignKey("PrescricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescricao");
                });

            modelBuilder.Entity("VetCare.API.Models.Mensagem", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VetCare.API.Models.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Paciente");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("VetCare.API.Models.MidiaSessao", b =>
                {
                    b.HasOne("VetCare.API.Models.AtendimentoFisioterapeutico", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VetCare.API.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("VetCare.API.Models.Notificacao", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VetCare.API.Models.ObservacaoInterna", b =>
                {
                    b.HasOne("VetCare.API.Models.AtendimentoFisioterapeutico", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VetCare.API.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.AvaliacaoClinica", "Avaliacao")
                        .WithMany()
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VetCare.API.Models.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Autor");

                    b.Navigation("Avaliacao");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("VetCare.API.Models.Pet", b =>
                {
                    b.HasOne("VetCare.API.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("VetCare.API.Models.Prescricao", b =>
                {
                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Prontuario", "Prontuario")
                        .WithMany()
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Prontuario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.Prontuario", b =>
                {
                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("VetCare.API.Models.Sessao", b =>
                {
                    b.HasOne("VetCare.API.Models.Tratamento", "Tratamento")
                        .WithMany("Sessoes")
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tratamento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.TokenRedefinicaoSenha", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VetCare.API.Models.Tratamento", b =>
                {
                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.Tutor", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VetCare.API.Models.Usuario", b =>
                {
                    b.HasOne("VetCare.API.Models.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("VetCare.API.Models.Vacina", b =>
                {
                    b.HasOne("VetCare.API.Models.Pet", "Paciente")
                        .WithMany("Vacinas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VetCare.API.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId");

                    b.Navigation("Paciente");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetCare.API.Models.VersaoRegistroClinico", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "AlteradoPor")
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlteradoPor");
                });

            modelBuilder.Entity("VetCare.API.Models.Veterinario", b =>
                {
                    b.HasOne("VetCare.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VetCare.API.Models.Pet", b =>
                {
                    b.Navigation("AlergiasCondicoes");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("VetCare.API.Models.Prescricao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("VetCare.API.Models.Tratamento", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("VetCare.API.Models.Tutor", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
